# Default values for techtrends.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: dxb-prod

replicaCount: 10

image:
  pullPolicy: Always


service:
  port: 7111

resources:
   limits:
     cpu: 500m
     memory: 256Mi
   requests:
     cpu: 300m
     memory: 128Mi


