# Default values for techtrends.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: staging

replicaCount: 3

service:
  port: 5111

resources: 
   limits:
     cpu: 500m
     memory: 128Mi
   requests:
     cpu: 300m
     memory: 90Mi


